version: '3'
services:
  grav:
    build:
      context: .
      args:
        GRAV_VERSION: 1.6.19
        ADMIN_USER: dev
        ADMIN_PASSWORD: Developer1
        ADMIN_EMAIL: ev@dev.dev
        ADMIN_PERMISSIONS: b
        ADMIN_FULLNAME: "Hagbard Celine"
        ADMIN_TITLE: God
    tty: true
    container_name: grav
    volumes:
      - grav:/var/www/html/
    ports:
      - "8000:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - default
    restart: always
volumes:
  grav:
    external: false
